### ISSUE TITLE
AttributeError: module 'pycocotools._mask' has no attribute 'iou'

### ISSUE THREAD

**Issue by lixiangpengcs** [MhLiao/MaskTextSpotterV3#10]
Hello, I configure the code as your suggestion. But when I run the demo, it raises an attribute error:

Traceback (most recent call last):
  File "tools/demo.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/modeling/detector/detectors.py", line 3, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 13, in <module>
    from ..rpn.rpn import build_rpn
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/modeling/rpn/rpn.py", line 8, in <module>
    from .loss import make_rpn_loss_evaluator
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/modeling/rpn/loss.py", line 16, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/structures/boxlist_ops.py", line 7, in <module>
    from maskrcnn_benchmark.structures.segmentation_mask import SegmentationMask
  File "/path/textDetection/MaskTextSpotterV3/maskrcnn_benchmark/structures/segmentation_mask.py", line 5, in <module>
    import pycocotools.mask as mask_utils
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/path/env/anaconda3/envs/masktextspotter/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/mask.py", line 76, in <module>
AttributeError: module 'pycocotools._mask' has no attribute 'iou'

May I ask the author that do you encounter this error? And how to solve this problem?

**Comment by MhLiao** [comment]
@lixiangpengcs [this](https://github.com/cocodataset/cocoapi/issues/59) may be helpful.

**Comment by lixiangpengcs** [comment]
I can import pycocotools._mask as _mask successfully. The current error is: 
AttributeError: module 'pycocotools._mask' has no attribute 'iou'

**Comment by MhLiao** [comment]
@lixiangpengcs [This reason](https://github.com/philferriere/cocoapi#why-am-i-getting-a-modulenotfounderror-no-module-named-pycocotools_mask-error-in-my-code) may be helpful. It says that 

> If you get this error, it is because the COCO library you are calling is NOT our version of the library. Instead, you are (inadvertently) referencing a local copy of the library. So, if you get this error, search the tree of import in your code for a reference to a local pycocotools library. Then, move or delete the local version.

**Comment by lixiangpengcs** [comment]
Thanks a lot. I will try as you suggested.

**Comment by lixiangpengcs** [comment]
Really thanks for your suggestion. It is right and I have solved this problem.
