### ISSUE TITLE
报错ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1,

### ISSUE THREAD

**Issue by HanazawaKanana** [MhLiao/MaskTextSpotterV3#31]
Traceback (most recent call last):
  File "tools/train_net.py", line 156, in <module>
    main()
  File "tools/train_net.py", line 152, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    start_iter=arguments["iteration"],
  File "/home/zhangmingzhou1/MaskTextSpotterV3-master/maskrcnn_benchmark/data/build.py", line 153, in make_data_loader
    datasets = build_dataset(cfg,dataset_list, transforms, DatasetCatalog, is_train)
  File "/home/zhangmingzhou1/MaskTextSpotterV3-master/maskrcnn_benchmark/data/build.py", line 43, in build_dataset
    dataset = factory(**args)
  File "/home/zhangmingzhou1/MaskTextSpotterV3-master/maskrcnn_benchmark/data/datasets/icdar.py", line 29, in __init__
    self.image_lists = self.filter_image_lists()
  File "/home/zhangmingzhou1/MaskTextSpotterV3-master/maskrcnn_benchmark/data/datasets/icdar.py", line 44, in filter_image_lists
    strs, loc = self.line2boxes(line)
  File "/home/zhangmingzhou1/MaskTextSpotterV3-master/maskrcnn_benchmark/data/datasets/icdar.py", line 228, in line2boxes
    loc = np.vstack((x1, y1, x2, y2, x3, y3, x4, y4)).transpose()
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1
Traceback (most recent call last):
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/zhangmingzhou1/anaconda3/envs/torch/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhangmingzhou1/anaconda3/envs/torch/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/pretrain/seg_rec_poly_fuse_feature.yaml']' returned non-zero exit status 1.

**Comment by MhLiao** [comment]
I guess this is because the segmentation proposal network fails to produce proposals at the early training period. You can use easier data at the beginning or use a pre-trained model.
