### ISSUE TITLE
No module named 'maskrcnn_benchmark.engine.launch'

### ISSUE THREAD

**Issue by TriplePool** [MhLiao/MaskTextSpotterV3#4]
Thank you for your excellent work.
I met an error in running training codes.
```
Traceback (most recent call last):
  File "tools/train_net.py", line 26, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 26, in <module>
    from maskrcnn_benchmark.engine.launch import launch
    from maskrcnn_benchmark.engine.launch import launchModuleNotFoundError
: No module named 'maskrcnn_benchmark.engine.launch'ModuleNotFoundError
: No module named 'maskrcnn_benchmark.engine.launch'
Traceback (most recent call last):
  File "tools/train_net.py", line 26, in <module>
    from maskrcnn_benchmark.engine.launch import launch
ModuleNotFoundError: No module named 'maskrcnn_benchmark.engine.launch'
Traceback (most recent call last):
  File "/home/gpu/miniconda3/envs/lomors/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gpu/miniconda3/envs/lomors/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gpu/miniconda3/envs/lomors/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/gpu/miniconda3/envs/lomors/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/gpu/miniconda3/envs/lomors/bin/python3', '-u', 'tools/train_net.py', '--local_rank=2', '--config-file', 'configs/pretrain/seg_rec_poly_fuse_feature.yaml']' returned non-zero exit status 1.
```

**Comment by MhLiao** [comment]
@TriplePool I am sorry that I uploaded a wrong training script. 
Now, it is updated. Please try it again.

**Comment by TriplePool** [comment]
> @TriplePool I am sorry that I uploaded a wrong training script.
> Now, it is updated. Please try it again.

I tried pretraining again, but met a new error.
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal                                  
Traceback (most recent call last):
  File "tools/train_net.py", line 153, in <module>
    main()
  File "tools/train_net.py", line 121, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/gpu/miniconda3/envs/lomors/lib/python3.7/site-packages/torch/cuda/__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/cuda/Module.cpp:59
```

**Comment by MhLiao** [comment]
@TriplePool Is the number of GPUs you used the same as `--nproc_per_node`?

**Comment by TriplePool** [comment]
> @TriplePool Is the number of GPUs you used the same as `--nproc_per_node`?

Thank you very much, I think this is why the error occurs.
How long does pre-training generally take? I have three 2080TI GPUs.

**Comment by MhLiao** [comment]
@TriplePool It should take several days (maybe 2~3 days for 8 GPUs. I forgot the specific time cost).  The eta may be large at the beginning due to the data loading.
